package me.abdelaziz.bytecode;

public enum OpCode {
    CONSTANT, NULL, TRUE, FALSE, POP,
    DEFINE_GLOBAL, GET_GLOBAL, SET_GLOBAL,
    GET_LOCAL, SET_LOCAL,
    GET_PROPERTY, SET_PROPERTY,
    GET_INDEX, SET_INDEX,
    ADD, SUBTRACT, MULTIPLY, DIVIDE, MODULO,
    EQUAL, GREATER, LESS, NOT, NEGATE,
    JUMP, JUMP_IF_FALSE, LOOP,
    CALL, CLOSURE, RETURN,
    CLASS, INHERIT, METHOD,
    ARRAY, MAP, CATALOG,
    TRY_BEGIN, TRY_END,
    HOLD, SPLIT,
    PRINT, PRINT_NOLINE,
    HALT
}